[[main]]
  name = "Archive"
  url = "archives/"
  weight = 5

[[main]]
  name = "Search"
  url = "search/"
  weight = 15

[[main]]
  name = "BucketList"
  url = "bucket_list/"
  weight = 20

[[main]]
  name = "GitHub Sponsors"
  url = "https://github.com/sponsors/nao1215"
  weight = 25
