[params]
  homeInfoParams = { Title = "Debimate", Content = "nchika(nao1215)の技術ブログ" }
  mainSections = ["post"]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  comments = false
  ShowImageInList = true
  ShowImageInSingle = true
  images = ["images/default-ogp.png"]
  enableSearch = true
  env = "production"
  enableOpenGraph = true
  enableTwitterCards = true


  [params.assets]
    css = ["css/extended/custom.css"]

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/nao1215"

[[params.socialIcons]]
  name = "rss"
  url = "index.xml"

[[params.socialIcons]]
  name = "twitter"
  url = "https://x.com/ARC_AED"

[[params.socialIcons]]
  name = "email"
  url = "mailto:n.chika156@gmail.com"