homeInfoParams = { Content = "nchika(nao1215)の技術ブログ。OSS、Go、人生について書きます。<br><br>私は組み込みからバックエンドにキャリアチェンジしており、Go、AWSをメインに使っています。現在は、プリカアプリ不正対策、機械学習、React Nativeをメインに勉強しています。" }

author = "nchika"
mainSections = ["post"]
defaultTheme = "auto"
ShowReadingTime = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
comments = false
ShowSocialIcons = true
ShowImageInList = true
ShowImageInSingle = true
ShowShareButtons = true
images = ["images/default-ogp.png"]
enableSearch = true
env = "production"
enableOpenGraph = true
enableTwitterCards = true
ShowRssButtonInSectionTermList = true

[assets]
  css = ["css/extended/custom.css"]

[[socialIcons]]
  name = "github"
  url = "https://github.com/nao1215"

[[socialIcons]]
  name = "rss"
  url = "index.xml"

[[socialIcons]]
  name = "twitter"
  url = "https://x.com/ARC_AED"

[[socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/nchika.bsky.social"

[[socialIcons]]
name = "dev"
url = "https://dev.to/nchika"

[[socialIcons]]
name = "hackerone"
url = "https://hackerone.com/nchika?type=user"

[[socialIcons]]
name = "kaggle"
url = "https://www.kaggle.com/nao1215"

[[socialIcons]]
  name = "email"
  url = "mailto:n.chika156@gmail.com"
