homeInfoParams = { Content = "nchika(nao1215)の技術ブログ。OSS、Go、人生について書きます。" }
mainSections = ["post"]
defaultTheme = "auto"
ShowReadingTime = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
comments = false
ShowSocialIcons = true
ShowImageInList = true
ShowImageInSingle = true
ShowShareButtons = true
images = ["images/default-ogp.png"]
enableSearch = true
env = "production"
enableOpenGraph = true
enableTwitterCards = true
ShowRssButtonInSectionTermList = true

[assets]
  css = ["css/extended/custom.css"]

[[socialIcons]]
  name = "github"
  url = "https://github.com/nao1215"

[[socialIcons]]
  name = "rss"
  url = "index.xml"

[[socialIcons]]
  name = "twitter"
  url = "https://x.com/ARC_AED"

[[socialIcons]]
  name = "email"
  url = "mailto:n.chika156@gmail.com"
